// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `do_send_files`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GLOBAL_APP_STATE`, `GLOBAL_DISCOVERY`, `GLOBAL_SERVER`, `GLOBAL_TRANSFER_PROGRESS`, `RUNTIME`, `TransferStatus`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`, `initialize`, `initialize`

/// Enable or disable chunk checksum verification.
/// Disabling gives ~10-15% speed boost on local networks.
void setChecksumEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleSetChecksumEnabled(enabled: enabled);

/// Get whether checksum verification is enabled.
bool getChecksumEnabled() =>
    RustLib.instance.api.crateApiSimpleGetChecksumEnabled();

/// Enable or disable file compression.
void setCompressionEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleSetCompressionEnabled(enabled: enabled);

/// Get whether file compression is enabled.
bool getCompressionEnabled() =>
    RustLib.instance.api.crateApiSimpleGetCompressionEnabled();

/// Get all current settings as JSON
Future<String> getSettings() =>
    RustLib.instance.api.crateApiSimpleGetSettings();

/// Start the background FastShare server and return some details
Future<String> startFastshare({
  required String downloadPath,
  required String tempPath,
}) => RustLib.instance.api.crateApiSimpleStartFastshare(
  downloadPath: downloadPath,
  tempPath: tempPath,
);

/// Send multiple files to a target IP
Future<String> sendFilesToIp({
  required List<String> filePaths,
  required String targetIp,
}) => RustLib.instance.api.crateApiSimpleSendFilesToIp(
  filePaths: filePaths,
  targetIp: targetIp,
);

/// Open a file or folder using the system default handler
Future<String> openFileInExplorer({required String path}) =>
    RustLib.instance.api.crateApiSimpleOpenFileInExplorer(path: path);

/// Get transfer history as JSON
Future<String> getTransferHistory() =>
    RustLib.instance.api.crateApiSimpleGetTransferHistory();

/// Trigger a network scan manually
Future<void> triggerDiscoveryScan() =>
    RustLib.instance.api.crateApiSimpleTriggerDiscoveryScan();

/// Get a list of discovered nearby devices in JSON format
Future<String> getNearbyDevices() =>
    RustLib.instance.api.crateApiSimpleGetNearbyDevices();

/// Get pending incoming transfer for UI popup, or null JSON if none. Returns {"file_id","from_addr","file_name"} or "null".
Future<String> getPendingIncoming() =>
    RustLib.instance.api.crateApiSimpleGetPendingIncoming();

/// Respond to incoming transfer (Accept = true, Decline = false). Call from Flutter when user taps Accept/Decline.
Future<void> respondIncoming({required String fileId, required bool accept}) =>
    RustLib.instance.api.crateApiSimpleRespondIncoming(
      fileId: fileId,
      accept: accept,
    );

/// Get progress of all active incoming transfers as JSON.
/// Returns a list of {"file_name", "progress", "total_bytes", "received_bytes"}
Future<String> getIncomingProgress() =>
    RustLib.instance.api.crateApiSimpleGetIncomingProgress();

/// Get outgoing transfer progress as JSON
Future<String> getOutgoingProgress() =>
    RustLib.instance.api.crateApiSimpleGetOutgoingProgress();
